<?php

/**
 * @file
 * Example of a module implementing a new skin for VSCC.
 *
 * This module intended as a template for your own skins.  To use it,
 * you must copy, rename, and adapt it. The end result should be a
 * ordinary Drupal module with "vscc" as a dependency.
 *
 * Note that this the example code assumes that the site's theme is
 * "bartik".  If you use anoher theme, you also need to change the
 * name of the theme function.
 *
 * See also: https://www.drupal.org/node/1599066
 */

/**
 * Implements hook_vscc_skin_info().
 */
function custom_vsccnewskin_vscc_skin_info() {
  return array(
    'sand_icons' => array(
      'name' => t('New icons'),
    )
  );
}

/**
 * Implements hook_theme().
 */
function custom_vsccnewskin_theme($existing, $type, $theme, $path) {
  return array(
    'vscc_element_sand_icons' => array(
      'variables' => array('element' => NULL, 'vss_id' => NULL, 'view' => NULL, 'settings' => array(), 'location' => NULL, 'rows' => array()),
    ),
  );
}

/**
 * Theme function pointing to images.
 *
 * Images may be kept anywhere. In this example they're in a
 * subdirectory of the vsccnewskin module.
 */
function corporateclean_vscc_element_sand_icons($vars) {
  $image_vars = array(
     // 'path' => drupal_get_path('theme', 'bartik') . '/images/vscc/sand_' . $vars['element'] . '.png',
    'path' => drupal_get_path('module', 'custom_vsccnewskin') . '/images/vscc/arrow_' . $vars['element'] . '.png',
    'alt' => t($vars['element']),
    'title' => t($vars['element']),
  );
  return theme('image', $image_vars);
}

function custom_vsccnewskin_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'documents_node_form') {
    // $result = db_select('field_data_field_user_service_line','n')
    //       ->fields('n',array('entity_id','field_user_service_line_tid'))
    //       ->execute()
    //       ->fetchAssoc();

  global $user;
  $user_fields = user_load($user->uid);  
  // echo '<pre>';
  // //print_r($user_fields->field_user_service_line['und']['0']['tid']);
  // echo '</pre>';
  $term = $user_fields->field_user_service_line['und']['0']['tid'];
  $term_parents = taxonomy_get_parents_all($user_fields->field_user_service_line['und']['0']['tid']);
  foreach($term_parents as $value) {
   $all_terms[] = $value->tid;
  }
  $term_ids = array();
  $term_ids['low'] = $all_terms[0];
  $term_ids['mid'] = $all_terms[1];
  $term_ids['high'] = $all_terms[2];
   drupal_add_js(array('jsVars' => $term_ids), array('type' => 'setting'));
  }

}

// function custom_vsccnewskin_form_alter(&$form, &$form_state, $form_id) { 
//   $termid = 1;
//     drupal_add_js(array('jsVars' => $termid), array('type' => 'setting'));
// }