<?php
/**
 * Implements hook_block_info().
 */
function custom_search_block_block_info() {
  $blocks = array();

  $blocks['customSearch'] = array(
    'info' => t('Custom search block'), 
    'region' => 'search_area',
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function custom_search_block_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'customSearch':
      $block['subject'] = t('');
      $block['content'] = drupal_get_form('custom_search_block_form');
    break;
  }
  return $block;
}

/**
 * Custom form.
 */
function custom_search_block_form($form, &$form_state) {
  $form['search_keyword'] = array(
    '#type' => 'textfield',
    '#title' => t('Search'),
    '#title_display' => 'invisible',
    '#size' => 15,
    '#default_value' => '',
    '#attributes' => array('title' => t('Enter the terms you wish to search for.')),
    '#attributes' => array('placeholder' => t('Search'))
  );
  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array('#type' => 'submit', '#value' => t('Go'));
  $form['#submit'][] = 'custom_search_block_form_submit';
  $path = drupal_get_path('module', 'custom_search_block');
  $form['#attached'] = array(
    'css' => array(
      'type' => 'file',
      'data' => $path . '/custom_search_block.css',
    ),
  );
  return $form;
}

/**
 * Custom form submit function.
 */
function custom_search_block_form_submit($form, &$form_state) {
  $keys = $form_state['values']['search_keyword'];
  if (isset($_POST['destination'])) {
    unset($_POST['destination']);
  }

  if ($form_state['values']['search_keyword'] == '') {
    form_set_error('keys', t('Please enter some keywords.'));
  }
  else {
    $form_state['redirect'] = array(
      'search-page',array('query' => array('search_api_views_fulltext' => $keys,),
      ),
    );
  }
}


/**
 * Implements hook_theme().
 */
function custom_search_block_theme() {
  return array(
    'custom_search_block_form' => array(
      'render element' => 'form',
      // 'template' => 'custom-search-block-form',
      // 'path' => drupal_get_path('module', 'custom_search_block'),
    ),
  );
}

/**
* Implements theme function()
*/
function theme_custom_search_block_form($variables) {
  $form = $variables['form'];
  //$output = '<h4>'.t('custom search block').'</h4>';
  $output = '<div class="custom-search-block-form">';
  $output .= '<div class="custom-search-textfield">';
  $output .= drupal_render($form['search_keyword']);
  $output .= '<div class="custom-search-button">';
  $output .= drupal_render($form['actions']['submit']);
  $output .= '</div>';
  $output .= '</div>';
  $output .= '</div>';
  $output .= drupal_render_children($form);
  return $output;
}


function custom_search_block_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  // if($form['#id'] == 'views-exposed-form-search-page-page') {
  //   drupal_set_message("Form ID is : " . $form['#id']);
  // }
  // $view = $form_state['view'];
  // if ($view->name == 'search_page' && $view->current_display == 'page') {
  //   echo '<pre>';
  //   print_r($form);
  //   echo '</pre>';
  //   exit();
  // }
}
// ?>